# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1e31a28e98a6647bc26a04ccce43745c74879f84a3980ccdb59e90ff474319d498d75b7b5cbbc138cf7884452d1005b794e913baa1a09005a54b0d52ea76dd9

test:
  secret_key_base: bb840d1df97fec5f693e797c44aefda1c2954d3210bd6a745ea28f0eebbedcffe7ababb6a99fb220b874068d0c951beafdb2fcdcdb4ccca9635a8af78afe190e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
